version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.9
        commands:
            - curl -sSL https://install.python-poetry.org | python3 - --version 1.4.2
            - export PATH=/root/.local/bin:$PATH
            - poetry env use system
            - poetry install
    pre_build:
        commands:
            - poetry run black --check */*.py */*/*.py
            - poetry run dvc status -q # If the pipeline is not up to date, the build is failed.
            - poetry run pytest # unit test
