stages:
  retrieve_data:
    cmd: poetry run retrieve_data
    deps:
      - pipelines/retrieve_data.py
    outs:
      - data/raw/hotels.parquet
  clean_data:
    cmd: poetry run clean_data
    deps:
      - pipelines/clean_data.py
      - data/raw/hotels.parquet
      - data/country_code.csv
    outs:
      - data/cleaned/bookings.parquet
  action_data:
    cmd: poetry run action_data
    deps:
      - pipelines/aggregate_data.py
      - data/cleaned/bookings.parquet
    outs:
      - data/aggregated/action.parquet